### ISSUE TITLE
.NET Core support

### ISSUE THREAD

**Issue by konard** [robertvazan/crc32c.net#1]
Are you going to support .NET Core?

**Comment by robertvazan** [comment]
I think that only managed implementation will work in .NET Core. Native libraries wouldn't work. I can add .NET Core support in the future, but I have other things to care about right now.

**Comment by konard** [comment]
PInvoke is supported on .NET Core. The trick is to find out how to pack libraries compiled for all platforms: Windows, Linux, macOS

**Comment by michaelp** [comment]
@robertvazan , I also need this library to support .net standard. what is your approach?

It might be helpful to take a look on how other projects dealt with this exact need. It might speed things up. Please let me know if you get stuck. I don't have much time but I will try to help as much as I can.

![lmdb](https://user-images.githubusercontent.com/3293/66079479-239b0c00-e532-11e9-940f-ff6819a61a1d.png)

**Comment by michaelp** [comment]
And also https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.nativelibrary?view=netcore-3.0 to simplify the NativeProxy.cs

**Comment by robertvazan** [comment]
This library is no longer maintained. Feed free to adopt it if you find it useful.
