### ISSUE TITLE
A strange potential memory leak

### ISSUE THREAD

**Issue by ywgATustcbbs** [robertvazan/crc32c.net#3]
I use this lib with protobuf. Then I found a sharp memory usage increase. Hence I traced stack and saw some strange huge string instances which I never used explicitly in mscorlib.dll 

I'm trying to figure out how to upload screenshot

**Comment by ywgATustcbbs** [comment]
My browser f**ks.

This is my stack trace results
![1](https://user-images.githubusercontent.com/11514506/73603956-b7eeab80-45c4-11ea-8034-7804117a5a56.png)
![2](https://user-images.githubusercontent.com/11514506/73603957-b8874200-45c4-11ea-989b-9de84ff72894.png)

After debuging, I found that if I commented out the crc32 line, memory usage would be normal.
Byte array that passed to that function was about 60MB.
![3](https://user-images.githubusercontent.com/11514506/73603958-b91fd880-45c4-11ea-80cf-d12e743f6710.png)
![4](https://user-images.githubusercontent.com/11514506/73603959-b91fd880-45c4-11ea-8218-2a8d8967ddb6.png)

The function only does one simple thing: to put crc32 at the end of byte[].
![5](https://user-images.githubusercontent.com/11514506/73603960-b9b86f00-45c4-11ea-8e05-f7c9fbc3d9e6.png)

**Comment by ywgATustcbbs** [comment]
I tried to write a smallest case, but failed, the case worked fine (there was a sharpe increase, but GC quickly released the memory). That's pretty strange.

**Comment by robertvazan** [comment]
Can you post here the body of the `ComputeCRC32CAndWriteToEnd(byte[])` method?

**Comment by ywgATustcbbs** [comment]
public void ComputeCRC32CAndWriteToEnd(byte[] src)
        {
            if (src.Length <= 4)
            {
                return;
            }
            uint a = Crc32C.Crc32CAlgorithm.Compute(src, 0, src.Length - 4);
            byte[] b = BitConverter.GetBytes(a);
            src[src.Length - 4] = b[0];
            src[src.Length - 3] = b[1];
            src[src.Length - 2] = b[2];
            src[src.Length - 1] = b[3];
            return;
        }

**Comment by robertvazan** [comment]
The native C++ code doesn't do any memory allocation. The only possible source of the leak is the P/Invoke code, but I fail to see how can [this code](https://github.com/robertvazan/crc32c.net/blob/master/Crc32C.NET/Native32.cs) leak memory. Per [fixed statement docs](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/fixed-statement), the memory is pinned only during execution of the `fixed` statement. Once the `fixed` statement completes, it is eligible for garbage collection.

Are you sure this memory leak is not just an artefact of garbage collector? Did you try to run [GC.Collect()](https://docs.microsoft.com/en-us/dotnet/api/system.gc.collect?view=netframework-4.8), perhaps even setting [LargeObjectHeapCompactionMode](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.gcsettings.largeobjectheapcompactionmode?view=netframework-4.8) to `CompactOnce` beforehand?

**Comment by ywgATustcbbs** [comment]
I did use multi threads in my code for netowrk io, the crc32 method was called just before socket.send method. And the byte[] was kept in a message object ( which was hold in a syncd queue) and released by another thread after server replied. The object was quick removed form queue (reference counter was 0) and the memory didn't come back to normal. 

When I wrote the smallest case. I first used single thread and found no memory leak. Then I copied the multi threads case, there seemed to be memory leak, the memory increased and quickly collected by GC.

I am confused now.

**Comment by ywgATustcbbs** [comment]
I used system.threading, is that the problem?

**Comment by robertvazan** [comment]
Threading is not a problem for Crc32C library. It can be safely called from multiple threads.

Since you say the memory is later reclaimed by GC, I believe this is either a GC artefact or a buffering somewhere in your program, likely in the networking layer. I am closing the issue.

**Comment by ywgATustcbbs** [comment]
Thank you.

 But I am wondering if it is a normal case that the memory usage for a 60M byte[] pushed to 1G+? If I use it for a 1G byte[] ( which is very likely in the future), dose it mean that I will encounter out of memory problem?

**Comment by robertvazan** [comment]
Crc32C.NET itself isn't causing the problem. It might be heap fragmentation, artefact of pinning (which Crc32C has to do), artefact of special handling of large objects in .NET's GC, buffering at several levels (app, .NET Framework, OS), or some GC peculiarity.

One last thing you could try is to use [SafeProxy](https://github.com/robertvazan/crc32c.net/blob/master/Crc32C.NET/SafeProxy.cs) (copy it to your sources), which is a managed-only implementation of CRC32-C.

**Comment by ywgATustcbbs** [comment]
OK, I will try you suggestions.

At first, I was confused by the 4 large string objects(300M+). I could not find them anywhere in my code. GC.collect() didn't kill them. So I was very concerned about my memory usage. Perhaps I should use somthing to walk around.
