### ISSUE TITLE
crc32c.net.signed package install fails

### ISSUE THREAD

**Issue by iq666** [robertvazan/crc32c.net#4]
Visual Studio 2019 latest release. 
Attempt to add package crc32c.net.signed to a .Net Framework 4.8 class library fails.
Adding crc32c.net package works however.

Severity	Code	Description	Project	File	Line	Suppression State
Error		Failed to add reference to 'Crc32C.crc32c32'.
Please make sure that the file is accessible, and that it is a valid assembly or COM component.

**Comment by austin99** [comment]
I'm having the same issue :( 
Did you figure out a solution or a workaround by any chance.  Thanks

**Comment by robertvazan** [comment]
This library is no longer maintained. Feed free to adopt it if you find it useful.
